### ISSUE TITLE
data file error 

### ISSUE THREAD

**Issue by Xls1994** [leebird/bionlp17#1]
Hi, when I use your code, I fail to load your data 'data.tar.gz'.
The error shows as follows:
`gzip:stdin: not in gzip format`
`tar: Child returned status 1`
`tar: Error is not recoverable: exiting now  `

Could you please provide your data again? Thanks

**Comment by leebird** [comment]
You can download it from here: http://biotm.cis.udel.edu/biotm/projects/ds/data.tar.gz

Will fix the file in the repo later.

Thanks.

**Comment by leebird** [comment]
Drop lfs as it's not free.. Use URL for data download instead.
